version: '3.8'

services:

  reverse-proxy:
    image: nginx:1.23.4-alpine
    container_name: music-app-proxy
    depends_on:
      - music-server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

  music-server:   
    image: music-api
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    container_name: music-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - .:/api
    environment:
      NODE_ENV: ${NODE_ENV}



